version: '3.0'

expectations:
  population_size: 10000

actions:
  # Study definition for objective 3
  # First for baseline tables
  generate_study_population_monitor_2018:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_monitor_bl --index-date-range "2018-03-01"
    outputs:
      highly_sensitive:
        cohort: output/input_monitor_bl_2018-03-01.csv
  
  generate_study_population_monitor_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_monitor_bl --index-date-range "2020-03-23"
    outputs:
      highly_sensitive:
        cohort: output/input_monitor_bl_2020-03-23.csv
  
  # Generate baseline tables objective 3
  baseline_monitor:
    run: stata-mp:latest analysis/check.do
    needs: [generate_study_population_monitor_2018, generate_study_population_monitor_2020]
    outputs:
      moderately_sensitive:
        log: logs/baseline.log
  
  #Study definition for outpatient objectives 1 & 2
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_op:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_op_meas --index-date-range "2019-04-01 to 2022-04-30 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_op_meas*.csv
  
  calculate_measures_op:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_op_meas --output-dir=output/measures
    needs: [generate_study_population_op]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_op_*_rate.csv

  generate_study_population_other:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_other --index-date-range "2018-03-01 to 2022-04-30 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_other*.csv
  
  calculate_measures_other:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_other --output-dir=output/measures
    needs: [generate_study_population_other]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_hosp_*_rate.csv
        measure_drug: output/measures/measure_med_*_rate.csv

  # Generate baseline tables
  graphs:
    run: stata-mp:latest analysis/graphs.do
    needs: [calculate_measures_op, calculate_measures_other]
    outputs:
      moderately_sensitive:
        log: logs/graphs.log
        graphs: output/graphs/line*.svg

  outpatients:
    run: stata-mp:latest analysis/outpatients.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/outpatients.log
        output: output/tables/op_*.csv
        tables: output/tables/characteristics*.csv

  time_series_checks:
    run: stata-mp:latest analysis/time_series_checks.do
    needs: [calculate_measures_other, calculate_measures_op]
    outputs: 
      moderately_sensitive: 
        log: logs/time_series_checks.log
        graphs: output/time_series/checks*.svg

  time_series:
    run: stata-mp:latest analysis/time_series.do
    needs: [calculate_measures_other, calculate_measures_op]
    outputs: 
      moderately_sensitive: 
        log: logs/time_series.log
        graphs: output/time_series/itsa*.svg
        tables: output/time_series/tsreg*.csv
  
  #Study definition for outpatient objectives - population for BSR abstract
  generate_study_population_bsr_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_bsr --index-date-range "2019-04-01" --output-dir=output/measures/op 
    outputs:
      highly_sensitive:
        cohort: output/measures/op/input_bsr_2019-04-01.csv

  generate_study_population_bsr_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_bsr --index-date-range "2020-04-01" --output-dir=output/measures/op 
    outputs:
      highly_sensitive:
        cohort: output/measures/op/input_bsr_2020-04-01.csv

  generate_study_population_bsr_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_bsr --index-date-range "2021-04-01" --output-dir=output/measures/op 
    outputs:
      highly_sensitive:
        cohort: output/measures/op/input_bsr_2021-04-01.csv
  bsr: 
    run: stata-mp:latest analysis/bsr.do
    needs: [generate_study_population_bsr_2019, generate_study_population_bsr_2020, generate_study_population_bsr_2021]
    outputs:
      moderately_sensitive:
        log: logs/bsr.log
        output: output/tables/bsr_*.csv
