version: '3.0'

expectations:
  population_size: 10000

actions:
  # Study definition for objective 3 - on hold
  # First for baseline tables
  # generate_study_population_monitor_2018:
  #  run: cohortextractor:latest generate_cohort --study-definition study_definition_monitor_bl --index-date-range "2018-03-01"
  #  outputs:
  #    highly_sensitive:
  #      cohort: output/input_monitor_bl_2018-03-01.csv
  
  #generate_study_population_monitor_2020:
  #  run: cohortextractor:latest generate_cohort --study-definition study_definition_monitor_bl --index-date-range "2020-03-23"
  #  outputs:
  #    highly_sensitive:
  #      cohort: output/input_monitor_bl_2020-03-23.csv
  
  # Generate baseline tables objective 3
  #baseline_monitor:
  #  run: stata-mp:latest analysis/check.do
  #  needs: [generate_study_population_monitor_2018, generate_study_population_monitor_2020]
  #  outputs:
  #    moderately_sensitive:
  #      log: logs/baseline.log
  
  # Study definition for flowchart
  generate_study_population_flowchart:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flowchart
    outputs:
      highly_sensitive:
        cohort: output/input_flowchart.csv
  flowchart:
    run: stata-mp:latest analysis/flowchart.do
    needs: [generate_study_population_flowchart]
    outputs:
      moderately_sensitive:
        log: logs/flowchart.log
        table: output/flowchart/values.txt
  #Study definition for outpatient objectives 1 & 2
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  
  
  #Static study population for measures
  
  generate_study_population_static:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static.csv
  #Study population for time-series
  generate_study_population_op:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_op_meas --index-date-range "2019-04-01 to 2022-03-31 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_op_meas*.csv

  join_cohorts:
    run: >
      cohort-joiner:v0.0.56
        --lhs output/measures/input_op_meas*.csv
        --rhs output/input_static.csv
        --output-dir output/measures/join/
    needs: [generate_study_population_op, generate_study_population_static]
    outputs: 
      highly_sensitive:
        cohort: output/measures/join/input_op*.csv
  
  calculate_measures_op:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_op_meas --output-dir=output/measures/join
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        measure: output/measures/join/measure_op_*_rate.csv
        measure_drug: output/measures/join/measure_med_*_rate.csv
        measure_hosp: output/measures/join/measure_hosp_*_rate.csv

  #generate_study_population_other:
  #  run: cohortextractor:latest generate_cohort --study-definition study_definition_other --index-date-range "2019-03-01 to 2022-03-31 by month" --output-dir=output/measures --output-format=csv
  #  outputs:
  #    highly_sensitive:
  #      cohort: output/measures/input_other*.csv
  
  #calculate_measures_other:
  #  run: cohortextractor:latest  generate_measures --study-definition study_definition_other --output-dir=output/measures
  #  needs: [generate_study_population_other]
  #  outputs:
  #    moderately_sensitive:
  #      measure: output/measures/measure_hosp_*_rate.csv
  #      measure_drug: output/measures/measure_med_*_rate.csv

  # Generate baseline tables
  graphs:
    run: stata-mp:latest analysis/graphs.do
    needs: [calculate_measures_op]
    outputs:
      moderately_sensitive:
        log: logs/graphs.log
        graphs: output/graphs/line*.svg

  outpatients:
    run: stata-mp:latest analysis/outpatients.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/outpatients.log
        output: output/tables/op_*.csv
        tables: output/tables/characteristics*.csv
        temp: output/tables/logistic*

  sankey:
    run: r:latest analysis/sankey.r
    needs: [generate_study_population]
    outputs: 
      moderately_sensitive:
        graphs: output/sankey_compact.csv

  time_series_checks:
    run: stata-mp:latest analysis/time_series_checks.do
    needs: [generate_study_population_op, calculate_measures_op]
    outputs: 
      moderately_sensitive: 
        log: logs/time_series_checks.log
        graphs: output/time_series/checks*.svg

  time_series:
    run: stata-mp:latest analysis/time_series.do
    needs: [calculate_measures_op]
    outputs: 
      moderately_sensitive: 
        log: logs/time_series.log
        graphs: output/time_series/itsa*.svg
        data: output/tables/all_itsa_output.csv
  
  #Study definition for outpatient objectives - population for BSR abstract
  generate_study_population_bsr_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_bsr --index-date-range "2019-04-01" --output-dir=output/measures
    outputs:
      highly_sensitive:
        #cohort: output/measures/op/input_bsr_2019-04-01.csv - file for BSR abstract 
        cohort: output/measures/input_bsr_2019-04-01.csv

  generate_study_population_bsr_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_bsr --index-date-range "2020-04-01" --output-dir=output/measures
    outputs:
      highly_sensitive:
        #cohort: output/measures/op/input_bsr_2020-04-01.csv - file for BSR abstract 
        cohort: output/measures/input_bsr_2020-04-01.csv

  generate_study_population_bsr_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_bsr --index-date-range "2021-04-01" --output-dir=output/measures
    outputs:
      highly_sensitive:
        #cohort: output/measures/op/input_bsr_2021-04-01.csv - file for BSR abstract 
        cohort: output/measures/input_bsr_2021-04-01.csv
  bsr: 
    run: stata-mp:latest analysis/bsr.do
    needs: [generate_study_population_bsr_2019, generate_study_population_bsr_2020, generate_study_population_bsr_2021]
    outputs:
      moderately_sensitive:
        log: logs/bsr.log
        output: output/op_long/bsr*.csv
