version: '3.0'

expectations:
  population_size: 1000

actions:
  #Study definition for outpatient objective (2)
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  outpatients:
    run: stata-mp:latest analysis/outpatients.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/outpatients.log